name: Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses and Install NDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager "ndk-bundle" "platform-tools" "platforms;android-28"

      - name: Download SDL2 Source
        run: |
          curl -L https://www.libsdl.org/release/SDL2-2.30.9.tar.gz -o sdl2.tar.gz
          tar -xzf sdl2.tar.gz
          mv SDL2-2.30.9 SDL2
          mkdir -p app/src/main/java/org/libsdl/app
          cp SDL2/android-project/app/src/main/java/org/libsdl/app/*.java app/src/main/java/org/libsdl/app/

      - name: Build Native Binaries
        run: |
          # Definimos o NDK_MODULE_PATH apontando para a pasta onde baixamos a SDL2
          $ANDROID_HOME/ndk-bundle/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=jni/Android.mk \
            NDK_APPLICATION_MK=jni/Application.mk \
            NDK_MODULE_PATH=./ \
            APP_PLATFORM=android-28
            
      - name: Build APK
        run: |
          gradle assembleDebug --stacktrace

      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
            name: jogo-debug-apk
            path: build/outputs/apks/debug/*.apk
