name: Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses and Install NDK
        run: |
          # Aceita todas as licenças pendentes do Google
          yes | sdkmanager --licenses
          # Instala a versão estável do NDK e as ferramentas necessárias
          sdkmanager "ndk-bundle" "platform-tools" "platforms;android-28"

      - name: Build Native Binaries
        run: |
          # Usamos o caminho absoluto do ANDROID_HOME para evitar erros de comando não encontrado
          $ANDROID_HOME/ndk-bundle/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=jni/Android.mk \
            NDK_APPLICATION_MK=jni/Application.mk \
            APP_PLATFORM=android-28

      - name: Upload Native Libs
        uses: actions/upload-artifact@v4
        with:
          name: bibliotecas-compiladas
          path: libs/
